1.0.4
free-audio/clap pull request #139
Opened 2022-07-12 09:25 UTC by abique

2022-07-12 11:49 UTC, robbert-vdh requested changes

2022-07-12 11:49 UTC, robbert-vdh commented on include/clap/ext/draft/state-context.h
> +/// This extension let the host save and load the plugin state for special purpose.
```suggestion
/// This extension lets the host save and load the plugin state with different semantics depending on the context.
```

2022-07-12 11:49 UTC, robbert-vdh commented on include/clap/ext/draft/state-context.h
> +/// }
Is this example necessary? I'm afraid a lot of people will not understand what this means without some additional context (heh). Just saying that the host may freely mix saving and loading operations from the state-context and state extensions and that the plugin should anticipate on that should be sufficient.

2022-07-15 08:27 UTC, abique commented
OK, I've reverted the latest change as I wasn't sure about it.
Let's go :-)

2022-07-16 09:47 UTC, Bremmers approved these changes

2022-07-16 10:17 UTC, baconpaul approved these changes
Looks good to me!

2022-07-19 05:12 UTC, abique commented
> My only question which I mentioned on discord: Do we want to put the menu extension in here in draft so we can try and implement it in bitwig/surge?

Is it ready? I remember that it still had open spec questions and there is no PR yet for it.
I think we can move on with 1.1.0 and as soon as the menu one is ready we make 1.2.0, unless the menu ext can be ready in the next few days?

2022-07-20 23:56 UTC, tim-janik commented
> > My only question which I mentioned on discord: Do we want to put the menu extension in here in draft so we can try and implement it in bitwig/surge?
> 
> Is it ready? I remember that it still had open spec questions and there is no PR yet for it. I think we can move on with 1.1.0 and as soon as the menu one is ready we make 1.2.0, unless the menu ext can be ready in the next few days?

I would recommend to wait and leave specs in draft/ until at least two implementations exist.

Fast iterations are great in the pre-1.0 aera or in draft state but not once things are official API/ABI and should not be deprecated/replaced for a couple years.

It is really easy for an implementation to support an additional "clap.foo.draft/99" interface string next to "clap.foo", but really hard to fix up an interface that lacks a tiny slot for an additional integer as state_context_t has just demonstrated.

2022-07-21 12:10 UTC, merged